spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://database-study-2.cdnxkpguqzfr.ap-northeast-2.rds.amazonaws.com/study-kyk
    driver-class-name: org.mariadb.jdbc.Driver
    username: nxmileadmin
    password: nxmileadmin12#
  jackson:
    deserialization:
      fail-on-unknown-properties: true